### ISSUE TITLE
DashboardAlert broke our dashboard

### ISSUE THREAD

**Issue by hideokamoto** [megumiteam/dc-pattern-lib-v2#13]
After replaced from Alert to DashboardAlert, our dashboard notification has been broken.
We re-replace the component to Alert.

If you fixed the issue, we can use it again.

### Wrapper
```js
const ExampleWrapperComponent = (props) => {
    const { type, message, title, hint } = props;
    return (
      <DashboardAlert type={type} isOpen={this.state.visible} toggle={this.onDismiss}>
        <b className="alert-heading">{title}</b>
        <br />
        {message}
        {hint}
      </DashboardAlert>
    );
  }
```

### Usage
```
<ExampleWrapperComponent type="danger" title="Failed to start WordPress" message="Error Code: ERR" />
```

## Expect
<img width="486" alt="スクリーンショット 2020-01-16 13 03 08" src="https://user-images.githubusercontent.com/6883571/72492647-4cd17500-3861-11ea-92dd-23aca78c5505.png">

## Actual
<img width="424" alt="スクリーンショット 2020-01-16 13 04 39" src="https://user-images.githubusercontent.com/6883571/72492716-8c985c80-3861-11ea-9ba9-e2cea82ebb80.png">

**Comment by emaildano** [comment]
https://github.com/megumiteam/dc-pattern-lib-v2/commit/c07eecaef1a29371371ab558b11938e3a1ee26fb
